// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kyllkrozprazwdrzwugq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5bGxrcm96cHJhendkcnp3dWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyNzUzODgsImV4cCI6MjA4Nzg1MTM4OH0._PXlfkxKQmT_gV23PahRaJzjaaX7Z30nucy0ix-SQvI";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);